apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: jarvis-console
  namespace: jarvis
  annotations:
    cert-manager.io/cluster-issuer: letsencrypt-prod
    traefik.ingress.kubernetes.io/router.entrypoints: websecure
spec:
  ingressClassName: traefik
  rules:
  - host: console.jarvis.local # User can change this
    http:
      paths:
      - path: /
        pathType: Prefix
        backend:
          service:
            name: jarvis-console
            port:
              number: 80
  tls:
  - hosts:
    - console.jarvis.local
    secretName: jarvis-console-tls
