apiVersion: v1
kind: Service
metadata:
  name: jarvis-console
  namespace: jarvis
  labels:
    app: jarvis-console
spec:
  ports:
  - port: 80
    targetPort: 3000
    protocol: TCP
    name: http
  selector:
    app: jarvis-console
