apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - deployment.yaml
  - cnpg-cluster.yaml
  # - service.yaml

images:
  - name: ghcr.io/lordmuffin/jarvis-router
    newTag: latest
