apiVersion: v1
kind: Service
metadata:
  name: jarvis-router
  namespace: jarvis
  labels:
    app: jarvis-router
spec:
  ports:
  - port: 8000
    targetPort: 8000
    protocol: TCP
    name: http
  selector:
    app: jarvis-router
