apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - ../../infrastructure/components/nats
  - ../../infrastructure/components/qdrant
  - ../../services/provocateur-interviewer
  - ../../services/router
  - ../../apps/jarvis-console
