package agent

import (
	"context"
	"fmt"
	"strings"
)

// Plan represents a sequence of actions generated by the agent.
type Plan struct {
	Steps []string
}

// Agent is the interface for the reasoning engine.
type Agent interface {
	Ask(ctx context.Context, prompt string) (Plan, error)
}

// GeminiAgent implements the Agent interface using Google Gemini (conceptually).
type GeminiAgent struct {
	APIKey string
}

// NewGeminiAgent creates a new instance of GeminiAgent.
func NewGeminiAgent(apiKey string) *GeminiAgent {
	return &GeminiAgent{APIKey: apiKey}
}

// Ask sends the user prompt to the agent and returns a Plan.
func (a *GeminiAgent) Ask(ctx context.Context, prompt string) (Plan, error) {
	// Mock implementation for the scaffold.
	// In a real implementation, this would call the Gemini API.
	
	// Simple keyword-based logic for demo purposes:
	var steps []string
	lowerPrompt := strings.ToLower(prompt)
	
	if strings.Contains(lowerPrompt, "list pods") {
		steps = append(steps, "RunKubectl: get pods")
	} else if strings.Contains(lowerPrompt, "deploy nginx") {
		steps = append(steps, "RunKubectl: run nginx --image=nginx --restart=Never")
	} else {
		// Default fallback plan
		steps = append(steps, fmt.Sprintf("Analyze request: %s", prompt))
		steps = append(steps, "Generate suggestion")
	}

	return Plan{Steps: steps}, nil
}
